name: translate

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'core/**'
      - 'desktop/**'
      - 'mobile/**'
      - 'plugin_info/**'
      - '.github/workflows/translations.yml'

jobs:
  auto-translate:
    uses: Mips2648/.github/.github/workflows/plugin-translate.yml@main
    secrets:
      DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}